MLTB/urls.py
from django.contrib import admin
from django.urls import path, include
from theory import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('theory/', include('theory.urls')),  # 算法原理
    path('performance/', include('performance.urls')),  # 算法性能分析
    path('example/', include('example.urls')),  # 算法应用
    path('index/', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('document/', views.document, name='document'),  # 文档
    path('about/', views.about, name='about'),
]

theory/urls.py
from django.urls import path
from theory import views

app_name = 'theory'
urlpatterns = [
    path('least_square_method/', views.least_square_method, name='LSM'),
    path('batch_gradient_descent/', views.batch_gradient_descent, name='BGD'),
    path('stochastic_gradient_descent/', views.stochastic_gradient_descent, name='SGD'),
    path('linear_simulation_data/', views.linear_simulation_data, name='LSD'),
    path('classify_simulation_data/', views.classify_simulation_data, name='classify_data'),
    path('cluster_simulation_data/', views.cluster_simulation_data, name='cluster_data'),
    path('license_plate_recognition/', views.license_plate_recognition, name='LPR'),
    path('k_nearest_neighbor/', views.k_nearest_neighbor, name='KNN'),
    path('linear_regression/', views.linear_regression, name='LR'),
    path('decision_tree/', views.decision_tree, name='DT'),
    path('deep_learnning/', views.deep_learnning, name='DL'),
    path('naive_bayes/', views.naive_bayes, name='NB'),
    path('ensemble_learning/', views.ensemble_learning, name='EL'),
    path('logistic_regression/', views.logistic_regression, name='LOR'),
    path('support_vector_machine/', views.support_vector_machine, name='SVM'),
    path('neural_network/', views.neural_network, name='NN'),
    path('k_means/', views.k_means, name='KM'),
]

theory/models.py
from django.db import models

# Create your models here.

theory/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
import json
from django.http import HttpResponse, JsonResponse
from theory.simulation_data import simulation_data
from sklearn.datasets.samples_generator import make_regression, make_classification, make_blobs
import numpy as np
from scipy import io as spio
from theory.kNearestNeighbor import KNN
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier


def index(request):
    return render(request, 'index.html')


def user_login(request):
    if request.method == "POST":
        user = authenticate(request, username=request.POST['nick_name'], password=request.POST['password'])
        if user is None:
            return render(request, 'login.html', {'error': '用户名或密码错误'})
        else:
            login(request, user)
            return render(request, 'algorithm/majorization/least_square_method.html', {'user_name': user})
    elif request.method == "GET":
        return render(request, 'login.html')


def user_logout(request):
    logout(request)
    return redirect('index')


def register(request):
    if request.method == "POST":
        register_form = UserCreationForm(request.POST)
        if register_form.is_valid():
            register_form.save()
            user = authenticate(username=register_form.cleaned_data['username'],
                                password=register_form.cleaned_data['password1'])
            login(request, user)
            return render(request, 'index.html', {'user_name': user})
    elif request.method == 'GET':
        return render(request, 'register.html')
    else:
        register_form = UserCreationForm()
    message = {'register_form': register_form}
    return render(request, 'algorithm/majorization/least_square_method.html', message)


def about(request):
    return render(request, 'about.html')


def document(request):
    return render(request, 'document/document.html')


def least_square_method(request):
    if request.method == 'POST':
        K = request.POST.get('k')
        B = request.POST.get('b')
        N_true = request.POST.get('N_true')
        N_noise = request.POST.get('N_noise')
        mu = request.POST.get('mu')
        sigma = request.POST.get('sigma')
        sim = simulation_data(float(K), float(B), float(N_true), float(N_noise), float(mu), float(sigma))
        json_data = sim.turn_json('LSM')
        return JsonResponse(json_data, safe=False)
    elif request.method == 'GET':
        sim = simulation_data()
        json_data = sim.turn_json('LSM')
        return render(request, 'algorithm/majorization/least_square_method.html',
                      {'data': json.dumps(json_data)})


def batch_gradient_descent(request):
    if request.method == 'POST':
        K = request.POST.get('k')
        B = request.POST.get('b')
        N_true = request.POST.get('N_true')
        N_noise = request.POST.get('N_noise')
        mu = request.POST.get('mu')
        sigma = request.POST.get('sigma')
        sim = simulation_data(float(K), float(B), float(N_true), float(N_noise), float(mu), float(sigma))
        json_data = sim.turn_json('BGD')
        return JsonResponse(json_data, safe=False)
    elif request.method == 'GET':
        sim = simulation_data()
        json_data = sim.turn_json('BGD')
        return render(request, 'algorithm/majorization/batch_gradient_descent.html',
                      {'data': json.dumps(json_data)})


def stochastic_gradient_descent(request):
    if request.method == 'POST':
        K = request.POST.get('k')
        B = request.POST.get('b')
        N_true = request.POST.get('N_true')
        N_noise = request.POST.get('N_noise')
        mu = request.POST.get('mu')
        sigma = request.POST.get('sigma')
        sim = simulation_data(float(K), float(B), float(N_true), float(N_noise), float(mu), float(sigma))
        json_data = sim.turn_json('SGD')
        return JsonResponse(json_data, safe=False)
    elif request.method == 'GET':
        sim = simulation_data()
        json_data = sim.turn_json('SGD')
        return render(request, 'algorithm/majorization/stochastic_gradient_descent.html',
                      {'data': json.dumps(json_data)})


def linear_simulation_data(request):
    if request.method == 'POST':
        n_samples = request.POST.get('n_samples')
        n_features = request.POST.get('n_features')
        n_redundant = request.POST.get('n_redundant')
        n_classes = request.POST.get('n_classes')
        n_clusters_per_class = request.POST.get('n_clusters_per_class')
        #print(float(n_samples), float(n_features), float(n_redundant), float(n_classes), float(n_clusters_per_class))
        # 初始化参数--------------------
        n_samples = int(n_samples)
        n_features = int(n_features)
        n_redundant = int(n_redundant)
        n_clusters_per_class = int(n_clusters_per_class)
        n_classes = int(n_classes)
        # 仿真数据生成------------------
        X1, Y1 = make_classification(n_samples=n_samples, n_features=n_features, n_redundant=n_redundant,
                                     n_clusters_per_class=n_clusters_per_class, n_classes=n_classes)

        # 仿真数据分组------------------
        def arr_turn(X1, Y1, n_classes, n_features):
            # 创建数组---------------
            def duplicate_checking_one(Y1, n_features):
                x = len(Y1)
                arr_x = np.zeros((x, n_features))
                return arr_x

            def duplicate_checking_two(Y1, n_features):
                x, y = 0, 0
                for i in range(0, len(Y1)):
                    if Y1[i] == 0:
                        x += 1
                    elif Y1[i] == 1:
                        y += 1
                arr_x = np.zeros((x, n_features))
                arr_y = np.zeros((y, n_features))
                return arr_x, arr_y

            def duplicate_checking_three(Y1, n_features):
                x, y, z = 0, 0, 0
                for i in range(0, len(Y1)):
                    if Y1[i] == 0:
                        x += 1
                    elif Y1[i] == 1:
                        y += 1
                    elif Y1[i] == 2:
                        z += 1
                arr_x = np.zeros((x, n_features))
                arr_y = np.zeros((y, n_features))
                arr_z = np.zeros((z, n_features))
                return arr_x, arr_y, arr_z,

            def duplicate_checking_four(Y1, n_features):
                x, y, z, q = 0, 0, 0, 0
                for i in range(0, len(Y1)):
                    if Y1[i] == 0:
                        x += 1
                    elif Y1[i] == 1:
                        y += 1
                    elif Y1[i] == 2:
                        z += 1
                    elif Y1[i] == 3:
                        q += 1
                arr_x = np.zeros((x, n_features))
                arr_y = np.zeros((y, n_features))
                arr_z = np.zeros((z, n_features))
                arr_q = np.zeros((q, n_features))
                return arr_x, arr_y, arr_z, arr_q

            if n_classes == 1:
                arr_x = duplicate_checking_one(Y1, n_features)
                for i in range(0, len(Y1)):
                    arr_x[i] = X1[i]
                return arr_x
            elif n_classes == 2:
                arr_x, arr_y = duplicate_checking_two(Y1, n_features)
                j, k = 0, 0
                for i in range(0, len(Y1)):
                    if Y1[i] == 0:
                        arr_x[j] = X1[i]
                        j += 1
                        continue
                    elif Y1[i] == 1:
                        arr_y[k] = X1[i]
                        k += 1
                return arr_x, arr_y
            elif n_classes == 3:
                arr_x, arr_y, arr_z = duplicate_checking_three(Y1, n_features)
                j, k, l = 0, 0, 0
                for i in range(0, len(Y1)):
                    if Y1[i] == 0:
                        arr_x[j] = X1[i]
                        j += 1
                        continue
                    elif Y1[i] == 1:
                        arr_y[k] = X1[i]
                        k += 1
                        continue
                    elif Y1[i] == 2:
                        arr_z[l] = X1[i]
                        l += 1
                return arr_x, arr_y, arr_z
            elif n_classes == 4:
                arr_x, arr_y, arr_z, arr_q = duplicate_checking_four(Y1, n_features)
                j, k, l, m = 0, 0, 0, 0
                for i in range(0, len(Y1)):
                    if Y1[i] == 0:
                        arr_x[j] = X1[i]
                        j += 1
                        continue
                    elif Y1[i] == 1:
                        arr_y[k] = X1[i]
                        k += 1
                        continue
                    elif Y1[i] == 2:
                        arr_z[l] = X1[i]
                        l += 1
                    elif Y1[i] == 3:
                        arr_q[m] = X1[i]
                        m += 1
                return arr_x, arr_y, arr_z, arr_q
            # ----------------------

        # ------------------------------

        json_data = {}
        if n_classes == 1:
            arr_x = arr_turn(X1, Y1, n_classes, n_features)
            json_data['data1'] = arr_x.tolist()
        elif n_classes == 2:
            arr_x, arr_y = arr_turn(X1, Y1, n_classes, n_features)
            json_data['data1'] = arr_x.tolist()
            json_data['data2'] = arr_y.tolist()
        elif n_classes == 3:
            arr_x, arr_y, arr_z = arr_turn(X1, Y1, n_classes, n_features)

templates/algorithm/theory/decision_tree.html
{% extends "base.html" %}
{% load static %}
{% block title_name %}决策树原理{% endblock title_name %}
{% block decision_tree_open %}menu-open{% endblock decision_tree_open %}
{% block decision_tree_light %}active{% endblock decision_tree_light %}
{% block dt_theory_light %}active{% endblock dt_theory_light %}
{% block main_part %}
    <h1>决策树算法原理</h1>
    <section class="col-lg-12 connectedSortable">
        <div id="main" style="width: 100%;height:600px;margin-top:3%;"></div>
    </section>
    <script>
        var dom = document.getElementById("main");
        var myChart = echarts.init(dom);
        myChart.showLoading();
        var data = {{ data|safe }};
        var app = {};
        option = null;
        myChart.hideLoading();
        myChart.setOption(option = {
            tooltip: {
                trigger: 'item',
                triggerOn: 'mousemove'
            },
            series: [
                {
                    type: 'tree',

                    data: [data],

                    left: '2%',
                    right: '2%',
                    top: '8%',
                    bottom: '20%',

                    symbol: 'emptyCircle',
                    symbolSize: 20,
                    orient: 'TB',

                    expandAndCollapse: true,

                    label: {
                        position: 'right',  // 标签的位置
                        distance: 80,
                        rotate: 0,  // 标签旋转多少度
                        //verticalAlign: 'middle',
                        align: 'right',
                        fontSize: 15
                    },
                    lineStyle: {
                        width: 5,
                        curveness: 1
                    },
                    leaves: {
                        label: {
                            position: 'bottom',
                            rotate: 0,  // 标签旋转多少度
                            verticalAlign: 'middle',
                            align: 'left'
                        }
                    },

                    animationDurationUpdate: 750
                }
            ]
        });

        if (option && typeof option === "object") {
            myChart.setOption(option, true);
        }
    </script>
{% endblock main_part %}

templates/algorithm/theory/deep_learnning.html
{% extends "base.html" %}
{% load static %}
{% block title_name %}深度学习原理{% endblock title_name %}
{% block deep_learning_open %}menu-open{% endblock deep_learning_open %}
{% block deep_learning_light %}active{% endblock deep_learning_light %}
{% block dl_theory_light %}active{% endblock dl_theory_light %}
{% block main_part %}
<h1>深度学习原理</h1>
{% endblock main_part %}

templates/algorithm/theory/ensemble_learning.html
{% extends "base.html" %}
{% load static %}
{% block title_name %}集成学习原理{% endblock title_name %}
{% block ensemble_learning_open %}menu-open{% endblock ensemble_learning_open %}
{% block ensemble_learning_light %}active{% endblock ensemble_learning_light %}
{% block el_theory_light %}active{% endblock el_theory_light %}
{% block main_part %}
<h1>集成学习算法原理</h1>
{% endblock main_part %}

templates/algorithm/theory/k_means.html
{% extends "base.html" %}
{% load static %}
{% block title_name %}K均值聚类原理{% endblock title_name %}
{% block k_means_open %}menu-open{% endblock k_means_open %}
{% block k_means_light %}active{% endblock k_means_light %}
{% block k_means_theory_light %}active{% endblock k_means_theory_light %}
{% block main_part %}
<h1>K均值聚类算法原理</h1>
{% endblock main_part %}

templates/algorithm/theory/k_nearest_neighbor.html
{% extends "base.html" %}
{% load static %}
{% block title_name %}K近邻原理{% endblock title_name %}
{% block k_nearest_neighbor_open %}menu-open{% endblock k_nearest_neighbor_open %}
{% block k_nearest_neighbor_light %}active{% endblock k_nearest_neighbor_light %}
{% block knn_theory_light %}active{% endblock knn_theory_light %}
{% block main_part %}
    <section class="col-lg-12 connectedSortable">
        <div id="container" style="width:1060px;height:800px;margin-top:3%;"></div>
    </section>
    <script>
        $(document).ready(function () {
            $(function () {
                var data = {{ data|safe }};
                drawBar("container", data);
            });
            var xData = [];
            var yData = [];
// 在键盘按下并释放及提交后验证提交表单
            $(function () {
                $("#signupForm").validate({
                    onkeyup: true,
                    rules: {
                        k: {
                            range: [1, 1000],
                            required: true
                        },
                        b: {
                            range: [1, 1000],
                            required: true
                        },
                        N_true: {
                            range: [10, 200],
                            required: true
                        },
                        N_noise: {
                            range: [10, 200],
                            required: true
                        },
                        mu: {
                            range: [1, 50],
                            required: true
                        },
                        sigma: {
                            range: [1, 50],
                            required: true
                        },
                    },
                    messages: {}
                });
            });

            //data = {};
            $.ajaxSetup({  // ajaxSetup() 方法为将来的 AJAX 请求设置默认值
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},  // data键表示规定要发送到服务器的数据
            });
            $('#tijiao').click(function () {  // 当提交表单时，会发生submit事件。该事件只适用于表单元素
                // submit()方法触发submit事件，或规定当发生submit事件时运行的函数
                if (!$("#signupForm").valid()) {
                    // alert("数据不合理!");
                    return;
                }
                data.k = $("#k").val();  // 对id为k的元素执行val()方法，以获取input输入的值
                data.b = $("#b").val();  // 同上
                data.N_true = $("#N_true").val();  // 同上
                data.N_noise = $("#N_noise").val();  // 同上
                data.mu = $("#mu").val();  // 同上
                data.sigma = $("#sigma").val();  // 同上
                $.ajax({  //ajax()方法用于执行 AJAX（异步 HTTP）请求，所有的jQuery AJAX方法都使用ajax()方法
                    type: "POST",  // 规定请求的类型（GET 或 POST）
                    data: data,  // 规定要发送到服务器的数据
                    url: "{% url 'theory:BGD' %}", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致
                    cache: false,  // 布尔值，表示浏览器是否缓存被请求页面。默认是 true
                    dataType: "json",  // 预期的服务器响应的数据类型
                    error: erryFunction,  //错误执行方法
                    success: succFunction //成功执行方法
                });

                function succFunction(data) {  // 当请求成功时运行的函数
                    drawBar("container", data);
                }

                function erryFunction() {
                    alert('数据请求错误！')
                }

                return false;
            });

            function drawBar(divId, data) {
                var myChart = echarts.init(document.getElementById(divId));
                var option = {
                    tooltip: {},
                    grid: {
                        right: 200,  //距离左侧
                        left: 200   //
                    },
                    xAxis: {
                        type: 'value',
                        data: xData,
                        max: data.X_max + 0.5,
                        min: data.X_min - 0.5,
                        scale: true,
                        splitNumber: 20,
                    },
                    yAxis: {
                        type: 'value',
                        data: yData,
                        max: data.Y_max + 0.5,
                        min: data.Y_min - 0.5,
                        scale: true,
                        splitNumber: 20,
                    },
                    visualMap: [{
                        show: true,
                        left: "50",
                        top: "30",
                        right: "auto",
                        bottom: "auto",
                        type: 'continuous',
                        min: 0,
                        max: 1,
                        calculable: true,
                        realtime: true,
                        dimension: 2,        //指定用数据的『哪个维度』，映射到视觉元素上。『数据』即 series.data。 可以把 series.data 理解成一个二维数组,其中每个列是一个维度,默认取 data 中最后一个维度
                        seriesIndex: 0,
                        splitNumber: 8,
                        inRange: {
                            symbol: 'circle',
                            color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
                        }
                    },
                        {
                            show: true,
                            left: "50",
                            top: "300",
                            right: "auto",
                            bottom: "auto",
                            type: 'continuous',
                            min: 0,
                            max: 1,
                            calculable: true,
                            realtime: true,
                            //dimension:1,        //指定用数据的『哪个维度』，映射到视觉元素上。『数据』即 series.data。 可以把 series.data 理解成一个二维数组,其中每个列是一个维度,默认取 data 中最后一个维度
                            seriesIndex: 1,
                            splitNumber: 8,
                            inRange: {
                                //symbol:'diamond',
                                color: ['#fee090', '#fdae61', '#f46d43']
                            }
                        }],
                    series: [{
                        name: 'Gaussian',
                        type: 'heatmap',
                        data: data.test_data,
                        itemStyle: {
                            emphasis: {
                                borderColor: '#333',
                                borderWidth: 1
                            }
                        },
                        progressive: 1000,
                        animation: false
                    },
                        {
                            type: 'scatter',
                            data: data.train_data
                        }]
                };
                myChart.setOption(option);
            }
        });
    </script>
{% endblock main_part %}

templates/algorithm/theory/linear_regression.html
{% extends "base.html" %}
{% load static %}
{% block title_name %}线性回归原理{% endblock title_name %}
{% block linear_regression_open %}menu-open{% endblock linear_regression_open %}
{% block linear_regression_light %}active{% endblock linear_regression_light %}
{% block lr_theory_light %}active{% endblock lr_theory_light %}
{% block main_part %}
<h1>线性回归算法原理</h1>
{% endblock main_part %}

templates/algorithm/theory/logistic_regression.html
{% extends "base.html" %}
{% load static %}
{% block title_name %}logistic回归原理{% endblock title_name %}
{% block logistic_regression_open %}menu-open{% endblock logistic_regression_open %}
{% block logistic_regression_light %}active{% endblock logistic_regression_light %}
{% block lor_theory_light %}active{% endblock lor_theory_light %}
{% block main_part %}
    <h1>logistic回归算法原理</h1>
{% endblock main_part %}

templates/algorithm/theory/naive_bayes.html
{% extends "base.html" %}
{% load static %}
{% block title_name %}朴素贝叶斯原理{% endblock title_name %}
{% block naive_bayes_open %}menu-open{% endblock naive_bayes_open %}
{% block naive_bayes_light %}active{% endblock naive_bayes_light %}
{% block nb_theory_light %}active{% endblock nb_theory_light %}
{% block main_part %}
<h1>朴素贝叶斯原理</h1>
{% endblock main_part %}

templates/algorithm/theory/neural_network.html
{% extends "base.html" %}
{% load static %}
{% block title_name %}神经网络原理{% endblock title_name %}
{% block neural_network_open %}menu-open{% endblock neural_network_open %}
{% block neural_network_light %}active{% endblock neural_network_light %}
{% block nn_theory_light %}active{% endblock nn_theory_light %}
{% block main_part %}
    <h1>神经网络算法原理</h1>
{% endblock main_part %}

templates/algorithm/theory/support_vector_machine.html
{% extends "base.html" %}
{% load static %}
{% block title_name %}支持向量机原理{% endblock title_name %}
{% block svm_open %}menu-open{% endblock svm_open %}
{% block svm_light %}active{% endblock svm_light %}
{% block svm_theory_light %}active{% endblock svm_theory_light %}
{% block main_part %}
<h1>支持向量机算法原理</h1>
    <section class="col-lg-12 connectedSortable">
        <div id="main" style="width: 100%;height:800px;margin-top:3%;"></div>
    </section>
    <script>
    var dom = document.getElementById("main");
    var myChart = echarts.init(dom);
    var app = {};
    option = null;
    myChart.showLoading({
        text: 'loading',
        color: 'blue',
        textColor: '#000',
        maskColor: 'rgba(255, 255, 255, 0.2)',
        zlevel: 0,
    });
    $.getScript('../../../static/js/simplex.js').done(function () {
        myChart.hideLoading();
        var noise = new SimplexNoise(Math.random);

        function generateData(theta, min, max) {
            var data = [];
            for (var i = 0; i <= 40; i++) {
                for (var j = 0; j <= 40; j++) {
                    for (var k = 0; k <= 40; k++) {
                        var value = noise.noise3D(i / 20, j / 20, k / 20);
                        valMax = Math.max(valMax, value);
                        valMin = Math.min(valMin, value);
                        data.push([i, j, k, value * 2 + 4]);
                    }
                }
            }
            return data;
        }

        var valMin = Infinity;
        var valMax = -Infinity;

        var data = generateData(2, -5, 5);

        myChart.setOption(option = {
            visualMap: {
                show: false,
                min: 2,
                max: 6,
                inRange: {
                    symbolSize: [0.5, 15],
                    color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026'],
                    colorAlpha: [0.2, 1]
                }
            },
            xAxis3D: {
                type: 'value'
            },
            yAxis3D: {
                type: 'value'
            },
            zAxis3D: {
                type: 'value'
            },
            grid3D: {
                axisLine: {
                    lineStyle: {color: '#fff'}
                },
                axisPointer: {
                    lineStyle: {color: '#fff'}
                },
                viewControl: {
                    projection: 'orthographic'
                }
            },
            series: [{
                type: 'scatter3D',
                data: data
            }]
        });

    });

    if (option && typeof option === "object") {
        myChart.setOption(option, true);
    }

</script>
{% endblock main_part %}